name: comprafacil_flutter
description: A new Flutter project for CompraFacil.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.6.0
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  geolocator: ^11.0.0
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.1
  path_provider: ^2.1.3
  dio: ^5.4.3+1
  flutter_local_notifications: ^17.1.2
  flutter_background_service: ^5.0.5
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.0
  ota_update: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
