name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [CompraFacil, CompraFacilAdmin]

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install
      working-directory: ${{ matrix.app }}

    - name: Generate Native Android Project
      run: npx expo prebuild --platform android --no-install
      working-directory: ${{ matrix.app }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ matrix.app }}/android

    - name: Build with Gradle (Release)
      run: ./gradlew assembleRelease
      working-directory: ${{ matrix.app }}/android

    - name: Uploading an Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.app }}-Release-APK
        path: ${{ matrix.app }}/android/app/build/outputs/apk/release/*.apk
