name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      build_android_store:
        description: 'Build Android Store App'
        required: true
        type: boolean
        default: true
      build_android_admin:
        description: 'Build Android Admin App'
        required: true
        type: boolean
        default: true
      build_web:
        description: 'Build Web Application'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      if: github.event_name != 'workflow_dispatch' || inputs.build_android_store || inputs.build_android_admin
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      if: github.event_name != 'workflow_dispatch' || inputs.build_android_store || inputs.build_android_admin
      run: chmod +x gradlew

    - name: Build Android Store App
      if: github.event_name != 'workflow_dispatch' || inputs.build_android_store
      run: ./gradlew :app:assembleDebug

    - name: Build Android Admin App
      if: github.event_name != 'workflow_dispatch' || inputs.build_android_admin
      run: ./gradlew :admin:assembleDebug

    - name: Set up Node.js
      if: github.event_name != 'workflow_dispatch' || inputs.build_web
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'web/package-lock.json'

    - name: Install Web Dependencies
      if: github.event_name != 'workflow_dispatch' || inputs.build_web
      run: |
        cd web
        npm install --legacy-peer-deps

    - name: Build Web Application
      if: github.event_name != 'workflow_dispatch' || inputs.build_web
      run: |
        cd web
        npm run build

    - name: Upload Web Artifact
      if: github.event_name != 'workflow_dispatch' || inputs.build_web
      uses: actions/upload-artifact@v4
      with:
        name: CompraFacil-Web-Bundle
        path: ./web/dist

    - name: Upload Store APK
      if: github.event_name != 'workflow_dispatch' || inputs.build_android_store
      uses: actions/upload-artifact@v4
      with:
        name: CompraFacil-Store-APK
        path: ./app/build/outputs/apk/debug/app-debug.apk

    - name: Upload Admin APK
      if: github.event_name != 'workflow_dispatch' || inputs.build_android_admin
      uses: actions/upload-artifact@v4
      with:
        name: CompraFacil-Admin-APK
        path: ./admin/build/outputs/apk/debug/admin-debug.apk
